---
- name: Ensure tailscale keyring directory exists
  ansible.builtin.file:
    path: "{{ _tailscale_keyring_dir }}"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Download tailscale gpg key
  ansible.builtin.get_url:
    url: "{{ _tailscale_keyring_url }}"
    dest: "{{ _tailscale_keyring_file }}"
    mode: '0644'
    owner: root
    group: root
  register: tailscale_keyring_downloaded

- name: Download tailscale repository configuration
  ansible.builtin.get_url:
    url: "{{ _tailscale_repo_url }}"
    dest: "{{ _tailscale_repo_file }}"
    mode: '0644'
    owner: root
    group: root
  register: tailscale_repo_added

- name: Ensure tailscale-initramfs keyring directory exists
  ansible.builtin.file:
    path: "{{ _tailscale_initramfs_keyring_dir }}"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Download tailscale-initramfs gpg key
  ansible.builtin.get_url:
    url: "{{ _tailscale_initramfs_keyring_url }}"
    dest: "{{ _tailscale_initramfs_keyring_file }}"
    mode: '0644'
    owner: root
    group: root
  register: tailscale_initramfs_keyring_downloaded

- name: Add tailscale-initramfs repository
  ansible.builtin.copy:
    content: "{{ _tailscale_initramfs_repo_line }}"
    dest: "{{ _tailscale_initramfs_repo_file }}"
    mode: '0644'
    owner: root
    group: root
  register: tailscale_initramfs_repo_added

- name: Update apt cache after adding repositories
  ansible.builtin.apt:
    update_cache: true
  when: >
    tailscale_keyring_downloaded.changed or
    tailscale_repo_added.changed or
    tailscale_initramfs_keyring_downloaded.changed or
    tailscale_initramfs_repo_added.changed

- name: Install tailscale
  ansible.builtin.apt:
    name: "{{ tailscale_packages }}"
    state: present

- name: Install tailscale-initramfs
  ansible.builtin.apt:
    name: "{{ tailscale_initramfs_packages }}"
    state: present
  notify: Update initramfs

- name: Ensure tailscale initramfs directory exists
  ansible.builtin.file:
    path: "{{ tailscale_initramfs_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Fail if no tailscale auth key provided
  ansible.builtin.fail:
    msg: |
      No tailscale auth key provided!
      Please set 'tailscale_authkey'.

      To generate an authentication key:
      - Go to https://login.tailscale.com/admin/settings/keys
      - Generate pre-approved key type with tag [tag:initramfs]

      Security warning: This key will be stored unencrypted in initramfs!
  when: tailscale_authkey == ""

- name: Generate tailscale initramfs config
  ansible.builtin.template:
    src: tailscale-config.j2
    dest: "{{ tailscale_initramfs_config_file }}"
    owner: root
    group: root
    mode: '0600'
  notify: Update initramfs

- name: Display hint - tailscale acls
  ansible.builtin.debug:
    msg: |
      For enhanced tailnet security, configure grants or acls (legacy)!
      - Go to https://login.tailscale.com/admin/acls
      - Define a policy to limit connectivity for devices with tag:initramfs
  tags: always
