---
- name: Ensure tailscale keyring directory exists
  file:
    path: "{{ _tailscale_keyring_dir }}"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Download tailscale gpg key
  get_url:
    url: "{{ _tailscale_keyring_url }}"
    dest: "{{ _tailscale_keyring_file }}"
    mode: '0644'
    owner: root
    group: root
  register: tailscale_keyring_downloaded

- name: Download tailscale repository configuration
  get_url:
    url: "{{ _tailscale_repo_url }}"
    dest: "{{ _tailscale_repo_file }}"
    mode: '0644'
    owner: root
    group: root
  register: tailscale_repo_added

# Repo setup for tailscale-initramfs

- name: Ensure tailscale-initramfs keyring directory exists
  file:
    path: "{{ _tailscale_initramfs_keyring_dir }}"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Download tailscale-initramfs gpg key
  get_url:
    url: "{{ _tailscale_initramfs_keyring_url }}"
    dest: "{{ _tailscale_initramfs_keyring_file }}"
    mode: '0644'
    owner: root
    group: root
  register: tailscale_initramfs_keyring_downloaded

- name: Add tailscale-initramfs repository
  copy:
    content: "{{ _tailscale_initramfs_repo_line }}"
    dest: "{{ _tailscale_initramfs_repo_file }}"
    mode: '0644'
    owner: root
    group: root
  register: tailscale_initramfs_repo_added

# Update cache

- name: Update apt cache after adding repositories
  apt:
    update_cache: yes
  when: >
    tailscale_keyring_downloaded.changed or 
    tailscale_repo_added.changed or
    tailscale_initramfs_keyring_downloaded.changed or
    tailscale_initramfs_repo_added.changed

- name: Install tailscale
  apt:
    name: "{{ tailscale_packages }}" 
    state: present

- name: Install tailscale-initramfs
  apt:
    name: "{{ tailscale_initramfs_packages }}"
    state: present
  notify: Update initramfs

- name: Ensure tailscale initramfs directory exists
  file:
    path: "{{ tailscale_initramfs_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Fail if no tailscale auth key provided
  fail:
    msg: |
      No tailscale auth key provided! 
      Please set 'tailscale_authkey'. 

      To generate an authentication key:
      - Go to https://login.tailscale.com/admin/settings/keys
      - Generate pre-approved key type with tag [tag:initramfs]
      
      Security warning: This key will be stored unencrypted in initramfs!
  when: tailscale_authkey == ""

- name: Generate tailscale initramfs config
  template:
    src: tailscale-config.j2
    dest: "{{ tailscale_initramfs_config_file }}"
    owner: root
    group: root
    mode: '0600'
  notify: Update initramfs

- name: Display hint - tailscale acls
  debug:
    msg: |
      For enhanced tailnet security, configure grants or acls (legacy)!
      - Go to https://login.tailscale.com/admin/acls
      - Define a policy to limit connectivity for devices with tag:initramfs
  tags: always
