---
- name: Install dropbear packages
  ansible.builtin.apt:
    name: "{{ dropbear_packages }}"
    state: present
    update_cache: true
  register: dropbear_packages_installed

- name: Ensure dropbear initramfs directory exists
  ansible.builtin.file:
    path: "{{ dropbear_initramfs_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Fail if no public ssh keys provided
  ansible.builtin.fail:
    msg: |
      No authorized keys provided!
      Please set 'dropbear_ssh_keys_unlock'.
  when: dropbear_ssh_keys_unlock | length == 0

- name: Generate authorized_keys for dropbear
  ansible.builtin.template:
    src: authorized_keys.j2
    dest: "{{ dropbear_authorized_keys_file }}"
    owner: root
    group: root
    mode: '0600'
  notify: Update initramfs

- name: Generate configuration for dropbear
  ansible.builtin.template:
    src: dropbear.conf.j2
    dest: "{{ dropbear_config_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: Update initramfs
